//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("demo.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolutionizing local business connectivity, our app seamlessly connects customers with nearby stores, fostering community support. Enjoy the convenience of doorstep delivery, enhancing the local shopping experience..
        /// </summary>
        internal static string about_app_desc {
            get {
                return ResourceManager.GetString("about_app_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string about_check_updates {
            get {
                return ResourceManager.GetString("about_check_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string about_contact_us {
            get {
                return ResourceManager.GetString("about_contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinira Confidential.
        /// </summary>
        internal static string about_copyright {
            get {
                return ResourceManager.GetString("about_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Center.
        /// </summary>
        internal static string about_helpCenter {
            get {
                return ResourceManager.GetString("about_helpCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string about_license {
            get {
                return ResourceManager.GetString("about_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agreement.
        /// </summary>
        internal static string about_user_agreement {
            get {
                return ResourceManager.GetString("about_user_agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string about_version {
            get {
                return ResourceManager.GetString("about_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        internal static string add_product {
            get {
                return ResourceManager.GetString("add_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localshoppy.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure.
        /// </summary>
        internal static string are_you_sure {
            get {
                return ResourceManager.GetString("are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby.
        /// </summary>
        internal static string baby {
            get {
                return ResourceManager.GetString("baby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Fashion 0 to 6 Months.
        /// </summary>
        internal static string baby0to6months {
            get {
                return ResourceManager.GetString("baby0to6months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Fashion 6 to 12 Months.
        /// </summary>
        internal static string baby6to12months {
            get {
                return ResourceManager.GetString("baby6to12months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Shop.
        /// </summary>
        internal static string character_shop {
            get {
                return ResourceManager.GetString("character_shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diapering.
        /// </summary>
        internal static string diapering {
            get {
                return ResourceManager.GetString("diapering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        internal static string electronics {
            get {
                return ResourceManager.GetString("electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Decor.
        /// </summary>
        internal static string home_decor {
            get {
                return ResourceManager.GetString("home_decor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids.
        /// </summary>
        internal static string kids {
            get {
                return ResourceManager.GetString("kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids Room.
        /// </summary>
        internal static string kids_room {
            get {
                return ResourceManager.GetString("kids_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Authentication ....
        /// </summary>
        internal static string login_check_authentication {
            get {
                return ResourceManager.GetString("login_check_authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string login_dont_hv_acnt {
            get {
                return ResourceManager.GetString("login_dont_hv_acnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string login_password {
            get {
                return ResourceManager.GetString("login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string login_signUp {
            get {
                return ResourceManager.GetString("login_signUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string login_username {
            get {
                return ResourceManager.GetString("login_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Localshoppy.
        /// </summary>
        internal static string login_welcomeNote {
            get {
                return ResourceManager.GetString("login_welcomeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        internal static string men {
            get {
                return ResourceManager.GetString("men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual Shoes.
        /// </summary>
        internal static string men_casualShoes {
            get {
                return ResourceManager.GetString("men_casualShoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formal Pants.
        /// </summary>
        internal static string men_formals {
            get {
                return ResourceManager.GetString("men_formals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formal Shirts.
        /// </summary>
        internal static string men_formalShirts {
            get {
                return ResourceManager.GetString("men_formalShirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formal Shoes.
        /// </summary>
        internal static string men_formalShoes {
            get {
                return ResourceManager.GetString("men_formalShoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grooming.
        /// </summary>
        internal static string men_grooming {
            get {
                return ResourceManager.GetString("men_grooming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeans.
        /// </summary>
        internal static string men_jeans {
            get {
                return ResourceManager.GetString("men_jeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-Shirts.
        /// </summary>
        internal static string men_tShirts {
            get {
                return ResourceManager.GetString("men_tShirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Product.
        /// </summary>
        internal static string scan_product {
            get {
                return ResourceManager.GetString("scan_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned Text.
        /// </summary>
        internal static string scanned_text {
            get {
                return ResourceManager.GetString("scanned_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirts 40.
        /// </summary>
        internal static string Shirt40 {
            get {
                return ResourceManager.GetString("Shirt40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        internal static string theme_dark {
            get {
                return ResourceManager.GetString("theme_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        internal static string theme_light {
            get {
                return ResourceManager.GetString("theme_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localshoppy.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toys.
        /// </summary>
        internal static string toys {
            get {
                return ResourceManager.GetString("toys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        internal static string women {
            get {
                return ResourceManager.GetString("women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to add?.
        /// </summary>
        internal static string you_want_to_add {
            get {
                return ResourceManager.GetString("you_want_to_add", resourceCulture);
            }
        }
    }
}
